import { Garment, CasualItem, ContextItem, OutfitCombination, AccessoryItem } from './types';

// DỮ LIỆU 11 VIỆT PHỤC GỐC
export const GARMENTS: Garment[] = [
  {
    id: "V01",
    name: "Áo dài tân thời",
    origin: "Phát triển từ áo ngũ thân tay chẽn thời Nguyễn. Bắt đầu cải biên mạnh mẽ từ thập niên 1930 với phong trào Le Mur (họa sĩ Cát Tường), Lê Phổ, tiếp tục định hình qua áo dài Raglan (thập niên 1960) và hoàn thiện thành phom dáng hiện đại.",
    characteristics: "Gồm 2 tà trước và sau dài chấm bắp chân hoặc gót chân; cổ cao hoặc tròn; tay raglan ráp chéo từ cổ nách; thân ôm sát eo tôn đường cong cơ thể; xẻ tà hai bên hông; mặc cùng quần lụa ống rộng dài chấm mu bàn chân.",
    usage_context: "Trang phục công sở, đồng phục học sinh/sinh viên, lễ tốt nghiệp, đám cưới hỏi, hội nghị quốc tế, ngày lễ Tết và các sự kiện ngoại giao.",
    colors: "Rất đa dạng. Trắng tinh khôi (học sinh), đỏ/hồng/vàng (cưới hỏi, lễ hội), pastel nhã nhặn hoặc sẫm màu (công sở, người trung niên).",
    accessories: "Giày cao gót bít mũi, mấn đội đầu (tùy dịp cưới hỏi), kiềng bạc/vàng, chuỗi ngọc trai, ví cầm tay.",
    significance: "Tôn vinh nét đẹp duyên dáng, kín đáo nhưng gợi cảm của phụ nữ Việt Nam; biểu tượng văn hóa quốc gia trong mắt bạn bè quốc tế.",
    notes: "Chọn nội y tệp màu da và phom dáng mượt mà để tránh hằn viền; chú ý độ hở eo hai bên tà để giữ tính lịch sự; tà áo dài dễ cuốn vào bánh xe khi di chuyển.",
    references: "Ngàn năm áo mũ (Trần Quang Đức); Trang phục Việt Nam (Đoàn Thị Tình).",
    type: "top",
    category: "top",
    gender: "unisex",
    formality: "formal",
    image_url: "assets/top/v01.png",
    has_gender_variants: true
  },
  {
    id: "V02",
    name: "Áo tứ thân",
    origin: "Trang phục dân gian truyền thống của phụ nữ vùng đồng bằng Bắc Bộ, hình thành từ trước thế kỷ 18 và phổ biến sâu rộng trong đời sống lao động nông nghiệp.",
    characteristics: "Thân áo xẻ giữa không cài cúc, dài qua gối. Lưng may ghép từ 2 mảnh vải (sống áo sau), phía trước là 2 tà rời được thắt nút trước bụng hoặc thả buông. Ống tay hẹp vừa phải; mặc lót áo yếm bên trong và khoác ngoài váy đầm xòe màu đen.",
    usage_context: "Lễ hội dân gian mùa xuân (hội Lim, hội đền Hùng), biểu diễn dân ca quan họ Bắc Ninh, diễn xướng dân gian.",
    colors: "Trang phục lao động mang màu nâu sồng, củ nâu, chàm; trang phục trẩy hội sử dụng tà áo ngoài màu tươi sáng (xanh cốm, hồng cánh sen, vàng mỡ gà) tương phản với váy đen.",
    accessories: "Nón quai thao (nón ba tầm), khăn mỏ quạ, dải yếm đào, thắt lưng bao lụa xanh/hồng, dép cong hoặc guốc mộc.",
    significance: "Biểu trưng cho sự tần tảo, mộc mạc và khéo léo của người phụ nữ thôn quê Bắc Bộ; bốn tà áo tượng trưng cho tứ thân phụ mẫu (cha mẹ mình và cha mẹ chồng).",
    notes: "Cần phân biệt rõ áo tứ thân mặc trẩy hội với trang phục diễn tuồng/chèo; khi mặc phải thắt nút tà áo hoặc bao lụa ngay ngắn, tránh để xộc xệch lộ yếm quá nhiều gây phản cảm.",
    references: "Trang phục phụ nữ các dân tộc Việt Nam (Viện Trang phục); Mỹ thuật thời Lê - Trịnh (Nguyễn Du Chi).",
    type: "outer",
    category: "outer_traditional",
    gender: "female",
    formality: "traditional",
    image_url: "assets/outer_traditional/v02.png"
  },
  {
    id: "V03",
    name: "Áo yếm",
    origin: "Đồ lót truyền thống của phụ nữ Việt, xuất hiện từ thời Lý - Trần và hoàn thiện phom dáng ổn định vào thời Hậu Lê - Nguyễn.",
    characteristics: "Tấm vải hình thoi hoặc vuông phủ kín ngực, cạnh trên khoét cong ôm cổ, cạnh dưới bo góc nhọn phủ xuống rốn. Cố định bằng hai dải dây buộc sau gáy và hai dải dây buộc ngang lưng. Có hai kiểu cổ chính: yếm cổ xây (khoét tròn kín đáo) và yếm cổ nhạn (khoét sâu chữ V).",
    usage_context: "Mặc lót bên trong áo tứ thân, áo cánh, áo ngũ thân; ngày nay dùng trong các bộ ảnh nghệ thuật, lễ hội dân gian hoặc biểu diễn múa truyền thống.",
    colors: "Phụ nữ lao động mặc yếm màu nâu, chàm; phụ nữ thị thành, trẩy hội chuộng yếm đào (hồng phấn), trắng ngà, xanh hồ thủy, đỏ son.",
    accessories: "Quần lĩnh, váy sồi đen, trâm cài tóc, dây chuyền bạc (nếu mặc cách tân).",
    significance: "Tượng trưng cho vẻ đẹp e ấp, đường nét cơ thể tự nhiên và đời sống nội tâm kín đáo của người phụ nữ phương Đông xưa.",
    notes: "Bản chất là nội y lót trong; tuyệt đối không mặc yếm trần đơn lẻ ra chốn công cộng, đền chùa hoặc các sự kiện trang nghiêm. Khi chụp ảnh nghệ thuật cần xử lý lớp lót/miếng dán ngực cẩn trọng.",
    references: "Đi tìm nét đẹp trang phục truyền thống (Trần Từ); Tìm hiểu trang phục Việt Nam (Đoàn Thị Tình).",
    type: "inner",
    category: "inner",
    gender: "female",
    formality: "casual",
    image_url: "assets/inner/v03.png"
  },
  {
    id: "V04",
    name: "Áo bà ba",
    origin: "Xuất hiện ở vùng Nam Bộ từ thế kỷ 19, chịu ảnh hưởng từ trang phục của người Ba-ba (nhóm người Hoa định cư tại vùng eo biển Malacca) kết hợp biến tấu với thói quen sinh hoạt vùng sông nước.",
    characteristics: "Thân áo xẻ giữa, vạt cài cúc suốt từ cổ xuống bụng; cổ tròn hoặc cổ tim; dáng áo ôm nhẹ theo thân nhưng không chiết eo gắt; tà xẻ cao vừa phải ở hai bên hông; có 2 túi vuông lớn phía trước; mặc kèm quần lụa/satin ống suông đen hoặc trắng.",
    usage_context: "Sinh hoạt đời thường miền Tây Nam Bộ, chợ nổi, lễ hội miệt vườn, biểu diễn đờn ca tài tử, tiếp đón khách du lịch trải nghiệm.",
    colors: "Đời thường mặc màu sẫm (đen, nâu nhuộm vỏ trâm bầu để chống bám phèn); dịp lễ tiệc dùng lụa màu mạ non, vàng nghệ, hồng phấn, tím cà.",
    accessories: "Khăn rằn Nam Bộ, nón lá, guốc mộc đơn giản, tóc thắt bím hoặc búi thấp.",
    significance: "Đại diện cho tính cách hào sảng, phóng khoáng, chất phác và mộc mạc của con người vùng đất phù sa sông Cửu Long.",
    notes: "Không nên may chít eo quá sát hoặc dùng vải xuyên thấu làm mất đi tinh thần thanh thoát, tự nhiên nguyên bản.",
    references: "Văn hóa Nam Bộ qua lăng kính trang phục (Sơn Nam); Lịch sử trang phục phương Nam (Nghiên cứu văn hóa dân gian).",
    type: "top",
    category: "top",
    gender: "unisex",
    formality: "casual",
    image_url: "assets/top/v04.png",
    has_gender_variants: true
  },
  {
    id: "V05",
    name: "Áo ngũ thân tay chẽn",
    origin: "Định hình từ cuộc cải cách trang phục của chúa Nguyễn Phúc Khoát ở Đàng Trong năm 1744, sau đó trở thành quốc phục chuẩn mực của triều Nguyễn từ thời vua Minh Mạng (1827–1837).",
    characteristics: "Thân áo ghép từ 5 khổ vải (2 thân trước, 2 thân sau, 1 thân con bên trong); phom suông đứng, không chít eo; cổ đứng cao ôm khép kín chân cổ; cài 5 khuy bên ngón phải; ống tay bó thon gọn từ khuỷu tay xuống cổ tay. Mặc cùng quần trắng (hoặc quần cùng màu) đáy rộng.",
    usage_context: "Sự kiện học thuật, hội thảo văn hóa, công sở, đi dạy học, chụp ảnh ngoại cảnh, lễ tết, sự kiện ngoại giao giao lưu văn hóa trẻ.",
    colors: "Nam giới thường mặc màu trầm, trung tính (xanh thẫm, đen, nâu, đỏ đun); nữ giới mặc các tông trang nhã (hồng đào, vàng hoa cúc, xanh ngọc, hoa văn dệt chìm).",
    accessories: "Khăn vấn (khăn đóng) chữ Nhân hoặc chữ Nhất, quạt xếp, đồng hồ đeo tay cổ điển, giày tây (nam), hài nhung hoặc guốc mộc.",
    significance: "5 thân áo tượng trưng cho 'tứ thân phụ mẫu' bảo bọc bản thân; 5 cúc tượng trưng cho ngũ thường (Nhân - Lễ - Nghĩa - Trí - Tín) hoặc ngũ luân; thể hiện sự tề chỉnh, nho nhã và giữ gìn lễ tiết.",
    notes: "Cổ áo phải thẳng đứng và ôm khít chân cổ; tà áo khi đứng buông thẳng nếp (dáng chữ A cân đối), không mặc xộc xệch hay để hở cổ bên trong (thường mặc kèm áo lót trắng/áo đơn bên trong).",
    references: "Khảo cứu trang phục triều Nguyễn (Trần Đình Sơn); Ngàn năm áo mũ (Trần Quang Đức).",
    type: "outer",
    category: "outer_traditional",
    gender: "unisex",
    formality: "traditional",
    image_url: "assets/outer_traditional/v05.png",
    has_gender_variants: true
  },
  {
    id: "V06",
    name: "Áo tấc (Áo ngũ thân tay thụng)",
    origin: "Lễ phục trang trọng thời Nguyễn (thế kỷ 19 – giữa thế kỷ 20), dùng cho mọi tầng lớp từ vua quan đến thứ dân trong các nghi lễ lớn.",
    characteristics: "Có cấu tạo thân và cổ đứng 5 khuy giống hệt áo ngũ thân tay chẽn, nhưng phần ống tay may thụng to bản (rộng từ 30–50 cm), chiều dài tay buông dài qua đầu ngón tay. Khi người mặc buông tay, tà tay rủ thẳng; khi khoanh tay chắp trước ngực tạo thành khung chữ nhật trang trọng.",
    usage_context: "Lễ tốt nghiệp đại học, bái đường hôn lễ, lễ tế đình/tổ tiên, viếng đền miếu, các sự kiện ngoại giao văn hóa cấp cao.",
    colors: "Xanh lam, đỏ đô, vàng nhạt, tím Huế, xanh lục ngọc; vải gấm dệt hoa văn chữ thọ, hoa cúc, mây cuộn.",
    accessories: "Khăn vấn chuẩn thức, quạt xếp bằng tre/gỗ, guốc mộc quai nhung hoặc giày thêu cổ.",
    significance: "Biểu thị sự tôn kính tuyệt đối đối với tiền nhân và nghi lễ; tư thế đứng khoanh tay giấu kín bàn tay trong ống thụng thể hiện sự khiêm cung, lễ phép.",
    notes: "Vì tay áo rất rộng và dài, tránh mặc khi phải di chuyển nhiều, chạy việc hậu cần hoặc ngồi ăn tiệc tự chọn (dễ chấm tà tay vào đồ ăn).",
    references: "Đại Nam hội điển sự lệ (Nội các triều Nguyễn); Tài liệu nghiên cứu của Trung tâm Bảo tồn Di tích Cố đô Huế.",
    type: "outer",
    category: "outer_traditional",
    gender: "unisex",
    formality: "formal",
    image_url: "assets/outer_traditional/v06.png"
  },
  {
    id: "V07",
    name: "Áo Nhật Bình",
    origin: "Thường phục của bậc Hoàng hậu, Hoàng thái hậu, Công chúa và Cung tần quý tộc triều Nguyễn; được luật định chặt chẽ trong điển chế cung đình.",
    characteristics: "Áo khoác ngoài dáng suông xẻ trước; điểm đặc trưng nhất là dải cổ áo to bản hình chữ nhật viền quanh cổ chạy dài xuống tận ngực; cố định vạt bằng dải vải buộc hoặc kim khánh/kim bội; tay áo có dải viền ngũ sắc rực rỡ (ngũ hành).",
    usage_context: "Lễ cưới hỏi hiện đại (cô dâu diện đón dâu), chụp ảnh nghệ thuật cưới, các lễ hội tái hiện văn hóa hoàng cung triều Nguyễn.",
    colors: "Cung đình quy định chặt chẽ theo phẩm bậc: Hoàng hậu dùng màu vàng chính sắc/cam; Công chúa dùng màu đỏ trần; Cung tần dùng màu tím, lục. Hiện nay ứng dụng linh hoạt hơn nhưng chủ yếu là đỏ, xanh, vàng, trắng.",
    accessories: "Khăn vành dây quấn nhiều vòng (hoặc khăn vấn), hài thêu phượng, hoa tai hạt ngọc, kiềng ngọc/kim khánh.",
    significance: "Biểu trưng cho sự quyền quý, đức hạnh và quy chuẩn lễ nghi chuẩn mực cao nhất của nữ giới chốn cung đình xưa.",
    notes: "Cần phân biệt rõ hoa văn và màu sắc giữa phẩm bậc xưa để không lạm dụng hoa văn rồng 5 móng; trang sức đi kèm cần tinh xảo, tránh các loại mấn đính cườm lòe loẹt kiểu sân khấu thị trường.",
    references: "Đại Nam thực lục (Quốc sử quán triều Nguyễn); Trang phục cung đình triều Nguyễn (Bảo tàng Cổ vật Cung đình Huế).",
    type: "outer",
    category: "outer_formal",
    gender: "female",
    formality: "formal",
    image_url: "assets/outer_formal/v07.png"
  },
  {
    id: "V08",
    name: "Áo Giao Lĩnh (Trực lĩnh vạt chéo)",
    origin: "Một trong những dạng cổ phục lâu đời nhất của người Việt, thịnh hành từ thời Lý, Trần, đạt đỉnh cao vào thời Lê sơ và Lê trung hưng (thế kỷ 15 – 18).",
    characteristics: "Cổ áo may nẹp thẳng nhưng khi mặc bắt chéo vạt bên trái đè lên vạt bên phải (tả nhẫm/hữu nhẫm), tạo thành đường viền cổ chữ V trước ngực; tay áo có thể là tay chẽn hoặc thụng lớn; cố định ngang eo bằng dây đai lụa buộc thắt.",
    usage_context: "Các sự kiện phục dựng lịch sử thời Lê, hội thảo học thuật cổ điển, biểu diễn nghi lễ cổ, chụp ảnh nghệ thuật điện ảnh cổ trang.",
    colors: "Thời Lê chuộng các màu tự nhiên: đỏ tía, xanh chàm, trắng ngà, vàng nhạt, đen, xanh rêu.",
    accessories: "Mũ tú tài, cân đai, dải ngọc bội (nếu là quý tộc), hài mũi cong, trâm gỗ/bạc.",
    significance: "Thể hiện trật tự văn hóa Nho giáo thời thịnh trị; phản ánh chiều sâu nghìn năm của văn minh Đại Việt trước thời kỳ áo cổ đứng thịnh hành.",
    notes: "Cực kỳ chú ý chiều vắt chéo cổ áo: luôn luôn vắt vạt trái đè lên phải (văn hóa người sống); tuyệt đối không vắt ngược lại (phải đè trái - theo phong tục cổ dùng cho người đã khuất).",
    references: "Ngàn năm áo mũ (Trần Quang Đức); Lịch triều hiến chương loại chí (Phan Huy Chú).",
    type: "outer",
    category: "outer_traditional",
    gender: "unisex",
    formality: "traditional",
    image_url: "assets/outer_traditional/v08.png",
    has_gender_variants: true
  },
  {
    id: "V09",
    name: "Áo Viên Lĩnh (Cổ tròn)",
    origin: "Phẩm phục quan lại và trang phục thịnh hành của nam giới từ thời Lý, Trần đến Lê; có nguồn gốc giao lưu văn hóa khu vực Đông Á cổ đại.",
    characteristics: "Cổ áo khoét tròn khép kín quanh chân cổ, cố định bằng nút cài bên vai phải; tay áo thường may thụng rộng; thân áo dài thụng phủ qua gối; ngực áo quan lại thường đính bổ tử (tấm thêu hình chim hoặc thú định phẩm trật).",
    usage_context: "Tế lễ thần linh/thành hoàng làng truyền thống, triển lãm phục dựng phục chế lịch sử, diễn xướng nghi thức lễ nghi cung đình thời Lê.",
    colors: "Phẩm cấp cao màu đỏ tươi, tím; phẩm cấp trung màu xanh lam; thường dân/nho sinh màu trầm, xanh sẫm hoặc trắng.",
    accessories: "Mũ Phốc Đầu (Ô sa mạo), đai lưng to bản (đai da/đai ngọc), hia đen mũi hếch, hốt ngà hoặc quạt lông.",
    significance: "Tượng trưng cho trật tự quy củ, sự uy nghiêm và cương vị quan chức, học vấn trong hệ thống nhà nước pháp quyền phong kiến Đại Việt xưa.",
    notes: "Đây phần lớn là phẩm phục quan lại; người mặc hiện nay cần hiểu rõ quy chuẩn bổ tử thêu trên ngực áo, tránh đính hình thêu sai phẩm hàm hoặc dùng đồ mô phỏng rẻ tiền.",
    references: "Khâm định Việt sử thông giám cương mục; Bản vẽ phục dựng của các hội nhóm nghiên cứu (Đại Việt Cổ Phong, Vietnam Centre).",
    type: "outer",
    category: "outer_traditional",
    gender: "unisex",
    formality: "formal",
    image_url: "assets/outer_traditional/v09.png",
    has_gender_variants: true
  },
  {
    id: "V10",
    name: "Áo Đối Khâm",
    origin: "Thịnh hành vào thời Lý - Trần - Hậu Lê; thường dùng làm áo khoác ngoài cho cả nam lẫn nữ, từ quý tộc tới dân gian.",
    characteristics: "Hai vạt áo phía trước may đối xứng song song, buông thẳng thả dọc theo hai bên thân chứ không vắt chéo qua nhau; không cài cúc giữa ngực mà để lộ lớp áo lót bên trong (như yếm hoặc giao lĩnh lót); ống tay thường rộng và suông rủ.",
    usage_context: "Lễ hội thời trang cổ phục, các buổi trình diễn nghệ thuật, chụp ảnh phong cách cổ phong.",
    colors: "Thường phối màu đối lập giữa áo khoác ngoài và áo trong (ngoài xanh - trong hồng, ngoài đỏ đun - trong trắng ngà) tạo tầng lớp thị giác.",
    accessories: "Dây đai lụa buộc lơi quanh eo, ngọc bội thả rủ, trâm cài tóc hoa kim loại, hài nhung.",
    significance: "Biểu hiện của sự thanh thoát, tự do, phóng khoáng trong mỹ cảm trang phục của người xưa; tạo cảm giác nhẹ nhàng, bay bổng.",
    notes: "Cần mặc lớp áo trong (yếm hoặc áo lót kín đáo) cẩn thận vì hai vạt áo khoác ngoài không khép kín, rất dễ hở nếu di chuyển nhanh hoặc trước gió lớn.",
    references: "Bản thảo nghiên cứu cổ phục Đại Việt; Các hiện vật lăng mộ thời Hậu Lê tại Bảo tàng Lịch sử Quốc gia.",
    type: "outer",
    category: "outer_formal",
    gender: "unisex",
    formality: "formal",
    image_url: "assets/outer_formal/v10.png"
  },
  {
    id: "v11",
    name: "Hài nhung",
    origin: "Hài nhung thuộc nhóm giày dép truyền thống có hình thức trang trọng, từng hiện diện trong hệ thống trang phục truyền thống và trang phục lễ nghi của người Việt, đặc biệt trong môi trường cung đình và tầng lớp có địa vị.",
    characteristics: "Dạng giày thấp, thường kín phần mũi và thân bàn chân; chất liệu mềm như nhung hoặc vải dày; đế thấp hoặc tương đối phẳng. Có thể được trang trí bằng chỉ thêu, hoa văn hoặc các họa tiết truyền thống.",
    usage_context: "Lễ nghi truyền thống, các dịp trang trọng, biểu diễn cổ phục, tái hiện trang phục lịch sử, lễ hội văn hóa và các hoạt động nghệ thuật mang yếu tố truyền thống.",
    colors: [
      "Đỏ",
      "Đỏ son",
      "Tím",
      "Xanh lam",
      "Xanh lục",
      "Đen",
      "Màu trầm"
    ],
    accessories: [
      "Áo ngũ thân",
      "Áo tấc",
      "Áo Nhật Bình",
      "Áo dài",
      "Trang phục truyền thống"
    ],
    significance: "Thể hiện sự trang trọng, chỉn chu và tính lễ nghi; góp phần hoàn thiện tổng thể hình ảnh của người mặc trong trang phục truyền thống.",
    notes: "Không nên sử dụng hài nhung như một loại giày hiện đại cho mọi hoàn cảnh. Khi phối với cổ phục cần chú ý đến thời kỳ, địa vị và giới tính của người mặc để tránh kết hợp tùy tiện giữa các hệ trang phục.",
    references: [
      "Ngàn năm áo mũ – Trần Quang Đức",
      "Trang phục Việt Nam – Đoàn Thị Tình",
      "Tư liệu về Việt phục và trang phục cung đình Việt Nam"
    ],
    type: "shoes",
    category: "traditional_footwear",
    gender: "female",
    formality: "Formal",
    image_url: "assets/traditional_footwear/v11.png"
  },
  {
    id: "v12",
    name: "Hài cung đình",
    origin: "Hài cung đình là nhóm giày dép mang tính nghi lễ gắn với môi trường cung đình Việt Nam, đặc biệt trong bối cảnh triều Nguyễn. Hình thức và mức độ trang trí có sự phân biệt theo thân phận, nghi lễ và loại trang phục đi kèm.",
    characteristics: "Thường có dáng kín chân, đế thấp và cấu tạo tương đối gọn. Có thể sử dụng chất liệu cao cấp và được trang trí bằng thêu, hoa văn hoặc các mô-típ mang tính nghi lễ. Một số loại có mũi cong hoặc hình dáng đặc trưng của giày hài truyền thống.",
    usage_context: "Không gian cung đình, nghi lễ triều đình, các dịp đại lễ và những hoàn cảnh có quy định chặt chẽ về trang phục. Ngày nay chủ yếu xuất hiện trong bảo tồn, phục dựng Việt phục, bảo tàng, sân khấu và các hoạt động văn hóa.",
    colors: [
      "Đỏ",
      "Vàng",
      "Đen",
      "Xanh",
      "Màu đậm"
    ],
    accessories: [
      "Áo Nhật Bình",
      "Áo tấc",
      "Áo ngũ thân",
      "Lễ phục cung đình"
    ],
    significance: "Thể hiện tính nghi lễ, địa vị và sự trang trọng trong văn hóa cung đình; đồng thời phản ánh sự phát triển của kỹ thuật dệt, thêu và chế tác phụ kiện trong lịch sử Việt Nam.",
    notes: "Không nên xem mọi loại hài cổ truyền là hài cung đình. Khi sử dụng trong dataset phục dựng lịch sử, nên xác định rõ hài thuộc bối cảnh cung đình hay dân gian và tránh gán các hoa văn biểu tượng cho hoàng tộc nếu không có căn cứ.",
    references: [
      "Ngàn năm áo mũ – Trần Quang Đức",
      "Trang phục Việt Nam – Đoàn Thị Tình",
      "Tư liệu về trang phục triều Nguyễn và di sản cung đình Huế"
    ],
    type: "shoes",
    category: "traditional_footwear",
    gender: "unisex",
    formality: "Formal",
    image_url: "assets/traditional_footwear/v12.png",
    has_gender_variants: true
  },
  {
    id: "v13",
    name: "Guốc mộc",
    origin: "Guốc mộc có lịch sử lâu đời trong đời sống người Việt. Trước khi giày dép hiện đại phổ biến, tre và gỗ là những vật liệu quen thuộc để chế tác guốc. Guốc gỗ mũi cong, quai bằng mây hoặc dây vải từng được sử dụng trong đời sống thường ngày và các dịp hội hè.",
    characteristics: "Thân guốc được đẽo từ gỗ thành một đế cứng, thường có phần mũi hơi cong lên. Guốc truyền thống có thể có quai bằng mây, vải hoặc các vật liệu khác. Một số guốc nữ được tạo độ lõm nhẹ ở phần giữa để ôm bàn chân; guốc nam thường có dáng thẳng và rộng hơn.",
    usage_context: "Đời sống thường ngày, đi chợ, đi hội, đi lễ và các sinh hoạt dân gian. Trong thế kỷ XX, guốc mộc còn trở thành phụ kiện thời trang phổ biến khi phối cùng áo dài, đặc biệt ở đô thị miền Nam. Ngày nay còn được sử dụng trong sân khấu, phim ảnh và các hoạt động tái hiện văn hóa.",
    colors: [
      "Màu gỗ tự nhiên",
      "Vàng nâu",
      "Nâu",
      "Đen"
    ],
    accessories: [
      "Áo dài",
      "Áo bà ba",
      "Áo the",
      "Khăn đóng",
      "Trang phục truyền thống",
      "Trang phục hoài cổ"
    ],
    significance: "Là một hình ảnh quen thuộc gắn với đời sống và thẩm mỹ truyền thống của người Việt. Khi phối với áo dài, guốc mộc góp phần tạo nên hình ảnh giản dị, duyên dáng và mang tính hoài niệm.",
    notes: "Đế gỗ cứng và có thể phát ra tiếng khi bước đi; không phù hợp với các hoạt động cần di chuyển nhanh hoặc địa hình trơn trượt. Khi phối cổ phục nên lựa chọn kiểu guốc phù hợp với thời kỳ và hoàn cảnh thay vì sử dụng mọi kiểu guốc cho mọi loại trang phục.",
    references: [
      "Trang phục Việt Nam – Đoàn Thị Tình",
      "Tư liệu về guốc mộc Việt Nam",
      "Cục Du lịch Quốc gia Việt Nam và các tư liệu về nghề làm guốc mộc"
    ],
    type: "shoes",
    category: "traditional_footwear",
    gender: "unisex",
    formality: "Casual",
    image_url: "assets/traditional_footwear/v13.png"
  }
];

// DỮ LIỆU ĐỒ HIỆN ĐẠI (CASUAL ITEMS)
export const CASUAL_ITEMS: CasualItem[] = [
  { id: "cs_01", name: "Quần Jeans ống rộng", type: "bottom", category: "bottom_pants", gender: "unisex", formality: "casual", silhouette: "Rộng", image_url: "assets/bottom_pants/cs_01.png" },
  { id: "cs_02", name: "Quần Skinny Jeans", type: "bottom", category: "bottom_pants", gender: "female", formality: "casual", silhouette: "Ôm", image_url: "assets/bottom_pants/cs_02.png" },
  { id: "cs_03", name: "Quần Tây ống suông", type: "bottom", category: "bottom_pants", gender: "unisex", formality: "smart-casual", silhouette: "Rộng", image_url: "assets/bottom_pants/cs_03.png" },
  { id: "cs_04", name: "Quần Culottes lụa/đũi", type: "bottom", category: "bottom_pants", gender: "unisex", formality: "smart-casual", silhouette: "Rộng", image_url: "assets/bottom_pants/cs_04.png" },
  { id: "cs_05", name: "Quần Shorts cạp cao", type: "bottom", category: "bottom_pants", gender: "female", formality: "casual", silhouette: "Rộng", image_url: "assets/bottom_pants/cs_05.png" },
  { id: "cs_06", name: "Chân váy chữ A", type: "bottom", category: "bottom_skirt", gender: "female", formality: "casual", silhouette: "Xòe", image_url: "assets/bottom_skirt/cs_06.png" },
  { id: "cs_07", name: "Chân váy Maxi xếp ly", type: "bottom", category: "bottom_skirt", gender: "female", formality: "smart-casual", silhouette: "Xòe", image_url: "assets/bottom_skirt/cs_07.png" },
  { id: "cs_08", name: "Chân váy bút chì", type: "bottom", category: "bottom_skirt", gender: "female", formality: "formal", silhouette: "Ôm", image_url: "assets/bottom_skirt/cs_08.png" },
  { id: "cs_09", name: "Chân váy xòe bồng Tulle", type: "bottom", category: "bottom_skirt", gender: "female", formality: "smart-casual", silhouette: "Xòe", image_url: "assets/bottom_skirt/cs_09.png" },
  { id: "cs_10", name: "Áo phông trắng basic", type: "inner", category: "inner", gender: "unisex", formality: "casual", silhouette: "Rộng", image_url: "assets/inner/cs_10.png" },
  { id: "cs_11_1", name: "Áo cổ lọ ôm sát", type: "inner", category: "inner", gender: "male", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/inner/cs_11_1.png" },
  { id: "cs_11_2", name: "Áo cổ lọ ôm sát", type: "inner", category: "inner", gender: "female", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/inner/cs_11_2.png" },
  { id: "cs_12", name: "Áo hai dây lụa", type: "inner", category: "inner", gender: "female", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/inner/cs_12.png" },
  { id: "cs_13_1", name: "Áo sơ mi trắng dáng suông", type: "inner", category: "inner", gender: "male", formality: "smart-casual", silhouette: "Rộng", image_url: "assets/inner/cs_13_1.png" },
  { id: "cs_13_2", name: "Áo sơ mi trắng dáng suông", type: "inner", category: "inner", gender: "female", formality: "smart-casual", silhouette: "Rộng", image_url: "assets/inner/cs_13_2.png" },
  { id: "cs_14", name: "Sneaker trắng tối giản", type: "shoes", category: "shoes", gender: "unisex", formality: "casual", silhouette: "Ôm", image_url: "assets/shoes/cs_14.png" },
  { id: "cs_15", name: "Giày Loafer da cổ điển", type: "shoes", category: "shoes", gender: "unisex", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/shoes/cs_15.png" },
  { id: "cs_16", name: "Giày Mary Jane gót thấp", type: "shoes", category: "shoes", gender: "female", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/shoes/cs_16.png" },
  { id: "cs_17", name: "Giày cao gót quai mảnh", type: "shoes", category: "shoes", gender: "female", formality: "formal", silhouette: "Ôm", image_url: "assets/shoes/cs_17.png" },
  { id: "cs_18", name: "Sandal bệt dây mảnh", type: "shoes", category: "shoes", gender: "female", formality: "casual", silhouette: "Ôm", image_url: "assets/shoes/cs_18.png" },
  { id: "cs_19_1", name: "Quần ống loe cạp cao", type: "bottom", category: "bottom_pants", gender: "male", formality: "smart-casual", silhouette: "Xòe", image_url: "assets/bottom_pants/cs_19_1.png" },
  { id: "cs_19_2", name: "Quần ống loe cạp cao", type: "bottom", category: "bottom_pants", gender: "female", formality: "smart-casual", silhouette: "Xòe", image_url: "assets/bottom_pants/cs_19_2.png" },
  { id: "cs_20", name: "Quần Linen ống suông rộng", type: "bottom", category: "bottom_pants", gender: "unisex", formality: "casual", silhouette: "Rộng", image_url: "assets/bottom_pants/cs_20.png" },
  { id: "cs_21", name: "Quần Bermuda Shorts may đo", type: "bottom", category: "bottom_pants", gender: "unisex", formality: "smart-casual", silhouette: "Rộng", image_url: "assets/bottom_pants/cs_21.png" },
  { id: "cs_22", name: "Chân váy lụa Satin dáng suông", type: "bottom", category: "bottom_skirt", gender: "female", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/bottom_skirt/cs_22.png" },
  { id: "cs_23", name: "Chân váy quấn", type: "bottom", category: "bottom_skirt", gender: "female", formality: "casual", silhouette: "Xòe", image_url: "assets/bottom_skirt/cs_23.png" },
  { id: "cs_24", name: "Chân váy xếp tầng Boho", type: "bottom", category: "bottom_skirt", gender: "female", formality: "casual", silhouette: "Xòe", image_url: "assets/bottom_skirt/cs_24.png" },
  { id: "cs_25", name: "Quần Legging trơn tối màu", type: "bottom", category: "bottom_pants", gender: "unisex", formality: "casual", silhouette: "Ôm", image_url: "assets/bottom_pants/cs_25.png" },
  { id: "cs_26", name: "Quần Baggy Kaki", type: "bottom", category: "bottom_pants", gender: "unisex", formality: "casual", silhouette: "Rộng", image_url: "assets/bottom_pants/cs_26.png" },
  { id: "cs_27", name: "Áo quây dệt kim / Chun ngực", type: "inner", category: "inner", gender: "female", formality: "casual", silhouette: "Ôm", image_url: "assets/inner/cs_27.png" },
  { id: "cs_28", name: "Áo Bodysuit cổ thuyền", type: "inner", category: "inner", gender: "female", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/inner/cs_28.png" },
  { id: "cs_29_1", name: "Áo Tank top gân tăm", type: "inner", category: "inner", gender: "male", formality: "casual", silhouette: "Ôm", image_url: "assets/inner/cs_29_1.png" },
  { id: "cs_29_2", name: "Áo Tank top gân tăm", type: "inner", category: "inner", gender: "female", formality: "casual", silhouette: "Ôm", image_url: "assets/inner/cs_29_2.png" },
  { id: "cs_30", name: "Áo Corset ren / Satin cách điệu", type: "inner", category: "inner", gender: "female", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/inner/cs_30.png" },
  { id: "cs_31", name: "Áo dệt kim cộc tay mỏng", type: "inner", category: "inner", gender: "unisex", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/inner/cs_31.png" },
  { id: "cs_32", name: "Áo sơ mi cổ tàu tối giản", type: "inner", category: "inner", gender: "unisex", formality: "smart-casual", silhouette: "Rộng", image_url: "assets/inner/cs_32.png" },
  { id: "cs_33", name: "Giày búp bê Ballet flats đính nơ", type: "shoes", category: "shoes", gender: "female", formality: "casual", silhouette: "Ôm", image_url: "assets/shoes/cs_33.png" },
  { id: "cs_34", name: "Giày Mule hở gót mũi nhọn", type: "shoes", category: "shoes", gender: "female", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/shoes/cs_34.png" },
  { id: "cs_35", name: "Guốc mộc cao gót", type: "shoes", category: "shoes", gender: "unisex", formality: "casual", silhouette: "Ôm", image_url: "assets/shoes/cs_35.png" },
  { id: "cs_36", name: "Boot cổ thấp da lì", type: "shoes", category: "shoes", gender: "unisex", formality: "smart-casual", silhouette: "Ôm", image_url: "assets/shoes/cs_36.png" },
  { id: "cs_37", name: "Giày Oxford cổ điển", type: "shoes", category: "shoes", gender: "unisex", formality: "formal", silhouette: "Ôm", image_url: "assets/shoes/cs_37.png" },
  { id: "cs_38", name: "Dép cói bệt dạo phố", type: "shoes", category: "shoes", gender: "unisex", formality: "casual", silhouette: "Ôm", image_url: "assets/shoes/cs_38.png" }
];

export const CONTEXTS: ContextItem[] = [
  {
    id: 'C05',
    name: 'Chốn linh thiêng (Đền, Chùa, Miếu, Lăng Tẩm)',
    description: 'Không gian tôn nghiêm, thờ tự tổ tiên và danh nhân văn hóa. Yêu cầu trang phục kín đáo, trang trọng.',
    is_sacred: true
  },
  {
    id: 'C01',
    name: 'Dạo phố & Không gian công cộng đương đại',
    description: 'Phố đi bộ, quán cà phê nghệ thuật, triển lãm và tuần lễ thời trang sáng tạo.',
    is_sacred: false
  },
  {
    id: 'C02',
    name: 'Lễ hội & Sự kiện văn hóa nghệ thuật',
    description: 'Sân khấu biểu diễn, sự kiện giao lưu văn hóa trong và ngoài nước.',
    is_sacred: false
  },
  {
    id: 'C03',
    name: 'Sự kiện trang trọng (Đám cưới, Kỷ niệm)',
    description: 'Những sự kiện yêu cầu tính thẩm mỹ, sang trọng và tôn trọng văn hóa.',
    is_sacred: false
  },
  {
    id: 'C04',
    name: 'Sự kiện học thuật, Hội thảo quốc tế',
    description: 'Yêu cầu trang phục thể hiện sự chuyên nghiệp, chuẩn mực và tri thức.',
    is_sacred: false
  },
  {
    id: 'C06',
    name: 'Concept Chụp ảnh Nghệ thuật',
    description: 'Linh hoạt thể hiện sự sáng tạo và tính nghệ thuật của người mặc.',
    is_sacred: false
  },
  {
    id: 'C07',
    name: 'Dịp Lễ Tết (Tết Nguyên Đán, Trung Thu)',
    description: 'Những dịp lễ hội quan trọng trong năm, yêu cầu trang phục tươi tắn, thanh lịch.',
    is_sacred: false
  }
];

export const OUTFIT_COMBINATIONS: OutfitCombination[] = [
  { id: "OF_01", name: "Nhật Bình Hoàng Triều Tinh Khôi", gender: "Female", applicable_events: ["C03", "C02", "C02"], style: "Royal formal heritage", composition: { inner: "cs_12", top: null, outer_formal: "V07", outer_traditional: null, bottom_pants: "cs_04", bottom_skirt: null, shoes: null, traditional_footwear: "v12_2", headwear: "Khăn vành dây", jewelry: ["j01", "j13"], other_accessories: ["Quạt xếp gấm thêu"] }, color_palette: { primary: "#C8102E", secondary: "#DAA520", accent: "#F5F5DC" }, styling_notes: "Áo Nhật Bình gấm lộng lẫy kết hợp lớp lót áo hai dây lụa kín đáo nhẹ nhàng bên trong, đi cùng quần culottes lụa ống rộng tôn dáng chuẩn mực cung đình. Hài cung đình thêu phụng và kiềng cổ hoàn thiện vẻ đẹp hoàng gia chuẩn thức.", traditional_focus: "Áo Nhật Bình - lễ phục hoàng triều triều Nguyễn mang dải cổ ngũ sắc tôn nghiêm.", rule_check_status: "UNDEFINED" },
  { id: "OF_02", name: "Nho Sinh Cung Kính - Áo Tấc Nam", gender: "Male", applicable_events: ["C03", "C07", "C02"], style: "Traditional formal elegance", composition: { inner: "cs_32", top: null, outer_formal: null, outer_traditional: "V06", bottom_pants: "cs_03", bottom_skirt: null, shoes: "cs_37", traditional_footwear: null, headwear: "h01_1", jewelry: ["j03"], other_accessories: ["Quạt xếp tre cổ điển"] }, color_palette: { primary: "#1A2B4C", secondary: "#FFFFFF", accent: "#8C7853" }, styling_notes: "Áo Tấc tay thụng trang trọng khoác ngoài sơ mi cổ tàu tối giản, phối với quần tây may đo phẳng phiu và giày Oxford da tạo diện mạo nho nhã, giữ trọn sự khiêm cung chuẩn mực.", traditional_focus: "Áo Tấc - lễ phục ngũ thân tay thụng thể hiện sự chỉn chu và tôn ti trật tự.", rule_check_status: "PASSED" },
  { id: "OF_03", name: "Hội Xuân Kinh Bắc - Tứ Thân Yếm Đào", gender: "Female", applicable_events: ["C02", "C02", "C06"], style: "Northern folk traditional", composition: { inner: "V03", top: null, outer_formal: null, outer_traditional: "V02", bottom_pants: null, bottom_skirt: "cs_23", shoes: null, traditional_footwear: "v13", headwear: "h03", jewelry: ["j01", "j14"], other_accessories: ["Dải thắt lưng bao lụa xanh"] }, color_palette: { primary: "#D4436E", secondary: "#1E1E1E", accent: "#2E8B57" }, styling_notes: "Bộ phối chuẩn mực văn hóa đồng bằng Bắc Bộ với áo tứ thân buông vạt lụa màu, mặc ngoài áo yếm đào e ấp, chân váy quấn đen tuyền, nón quai thao tráng lệ và guốc mộc dân gian.", traditional_focus: "Áo tứ thân kết hợp Áo yếm đại diện cho di sản trang phục trẩy hội dân gian Kinh Bắc.", rule_check_status: "PASSED" },
  { id: "OF_04", name: "Hà Thành Duyên Dáng - Áo Dài Tân Thời Nữ", gender: "Female", applicable_events: ["C07", "C06", "C02"], style: "Classic elegant Ao Dai", composition: { inner: null, top: "V01_2", outer_formal: null, outer_traditional: null, bottom_pants: "cs_04", bottom_skirt: null, shoes: "cs_17", traditional_footwear: null, headwear: "h04_2", jewelry: ["j17", "j18"], other_accessories: ["Ví cầm tay lụa thêu hoa sen"] }, color_palette: { primary: "#E8A598", secondary: "#FFFFFF", accent: "#C5A059" }, styling_notes: "Áo dài tân thời dáng ôm tôn đường cong duyên dáng phối cùng quần culottes lụa suông rộng, điểm xuyết mấn đội đầu và khuyên tai ngọc trai thanh lịch, bước đi trên giày cao gót thanh mảnh quý phái.", traditional_focus: "Áo dài tân thời nữ - biểu tượng quốc phục tôn vinh vẻ đẹp kín đáo mà thướt tha của phụ nữ Việt.", rule_check_status: "PASSED" },
  { id: "OF_05", name: "Tân Thời Quý Phái - Áo Dài Nam Cách Tân", gender: "Male", applicable_events: ["C02", "C03", "C07"], style: "Modern gentleman fusion", composition: { inner: null, top: "V01_1", outer_formal: null, outer_traditional: null, bottom_pants: "cs_03", bottom_skirt: null, shoes: "cs_15", traditional_footwear: null, headwear: null, jewelry: ["j07"], other_accessories: ["Đồng hồ dây da cổ điển"] }, color_palette: { primary: "#2C3E50", secondary: "#E0E0E0", accent: "#8E44AD" }, styling_notes: "Áo dài tân thời nam phom đứng cứng cáp phối hiện đại cùng quần tây ống suông và giày loafer da nâu bóng, mang đến phong thái đĩnh đạc, giao hòa giữa tinh hoa truyền thống và nét lịch lãm đương đại.", traditional_focus: "Áo dài tân thời nam giữ nét trang nghiêm nhưng hòa nhập nhịp sống hiện đại.", rule_check_status: "PASSED" },
  { id: "OF_06", name: "Cổ Phong Diễm Lệ - Đối Khâm & Yếm", gender: "Female", applicable_events: ["C06", "C02", "C02"], style: "Heritage vintage layering", composition: { inner: "V03", top: null, outer_formal: "V10", outer_traditional: null, bottom_pants: null, bottom_skirt: "cs_07", shoes: null, traditional_footwear: "v11", headwear: null, jewelry: ["j05", "j10", "j19"], other_accessories: ["Dây đai thắt lụa buông rủ"] }, color_palette: { primary: "#5B8266", secondary: "#E3C565", accent: "#FAF0CA" }, styling_notes: "Áo Đối Khâm khoác buông hai vạt song song để lộ lớp áo yếm lụa kín đáo bên trong, phối chân váy maxi xếp ly bồng bềnh và hài nhung thêu chỉ, tạo chiều sâu thị giác đa tầng tao nhã.", traditional_focus: "Áo Đối Khâm kết hợp Áo yếm  thể hiện nét thanh thoát, phóng khoáng của cổ phục thời Lê.", rule_check_status: "PASSED" },
  { id: "OF_07", name: "Phố Thị Giao Thoa - Ngũ Thân Nam & Denim", gender: "Male", applicable_events: ["C01", "C02", "C06"], style: "Traditional modern fusion", composition: { inner: "cs_32", "top": null, outer_formal: null, outer_traditional: "V05_1", bottom_pants: "cs_01", bottom_skirt: null, shoes: "cs_15", traditional_footwear: null, headwear: null, jewelry: ["j04"], other_accessories: ["Kính râm gọng tròn cổ điển"] }, color_palette: { primary: "#34495E", secondary: "#4A69BD", accent: "#F8C291" }, styling_notes: "Áo ngũ thân tay chẽn nam phom suông cổ đứng phối phá cách nhưng hài hòa cùng quần jeans ống rộng và giày loafer da, tạo phong cách dạo phố trẻ trung đậm bản sắc di sản.", traditional_focus: "Áo ngũ thân tay chẽn nam đại diện cho quốc phục triều Nguyễn được ứng dụng sáng tạo vào đời sống thường nhật.", "rule_check_status": "PASSED" },
  { id: "OF_08", name: "Nét Xưa Đoan Trang - Ngũ Thân Nữ & Khăn Vấn", gender: "Female", applicable_events: ["C07", "C02", "C03"], style: "Neo-traditional classic", composition: { inner: "cs_11_2", "top": null, outer_formal: null, outer_traditional: "V05_2", bottom_pants: "cs_04", bottom_skirt: null, shoes: null, traditional_footwear: "v11", headwear: "h01_2", jewelry: ["j01", "j06"], other_accessories: ["Túi cói thêu tay mộc mạc"] }, color_palette: { primary: "#8E44AD", secondary: "#ECF0F1", accent: "#27AE60" }, styling_notes: "Áo ngũ thân tay chẽn nữ màu tím trang nhã lót áo cổ lọ ấm áp, kết hợp quần culottes lụa trắng và hài nhung tím, điểm xuyết khăn vấn tóc truyền thống và kiềng cổ tôn vinh vẻ đoan trang mực thước.", traditional_focus: "Áo ngũ thân tay chẽn nữ thể hiện nếp sống gia lễ và mỹ cảm nền nã của phụ nữ phương Đông.", "rule_check_status": "PASSED" },
  { id: "OF_09", name: "Đại Việt Cổ Kính - Giao Lĩnh Nam Tiên Sinh", gender: "Male", applicable_events: ["C02", "C02", "C06"], style: "Historic scholarly look", composition: { inner: "cs_32", "top": null, outer_formal: null, outer_traditional: "V08_1", bottom_pants: "cs_20", bottom_skirt: null, shoes: "cs_37", traditional_footwear: null, headwear: null, jewelry: ["j19"], other_accessories: ["Đai lưng lụa buộc eo", "Túi gấm đeo hông"] }, color_palette: { primary: "#2F4F4F", secondary: "#F5F5DC", accent: "#8B0000" }, styling_notes: "Áo Giao Lĩnh nam bắt chéo vạt trái đè vạt phải nghiêm ngặt theo quy chuẩn hữu nhẫm, phối cùng quần linen ống suông thoáng mát và giày Oxford da, toát lên phong thái nho nhã của kẻ sĩ thời Lê.", traditional_focus: "Áo Giao Lĩnh nam khơi gợi diện mạo cổ phục Đại Việt thời Lê sơ - Lê trung hưng.", "rule_check_status": "PASSED" },
  { id: "OF_10", name: "Giao Lĩnh Thục Nữ - Sắc Biển Trầm Mặc", gender: "Female", applicable_events: ["C06", "C02", "C02"], style: "Classical ethereal fusion", composition: { inner: "cs_11_2", "top": null, outer_formal: null, outer_traditional: "V08_2", bottom_pants: null, bottom_skirt: "cs_07", shoes: "cs_34", traditional_footwear: null, headwear: null, jewelry: ["j06", "j19"], other_accessories: ["Quạt lụa tròn thêu hoa thủy tiên"] }, color_palette: { primary: "#3B5998", secondary: "#E8ECEF", accent: "#48C9B0" }, styling_notes: "Áo Giao Lĩnh nữ vạt chéo chữ V chuẩn mực tôn cần cổ cao, kết hợp chân váy maxi xếp ly rủ mềm mại và giày mule mũi nhọn thời thượng, phối vòng ngọc bích tạo vẻ đẹp thanh tao, thoát tục.", traditional_focus: "Áo Giao Lĩnh nữ chuẩn nẹp cổ vắt tả nhẫm tôn vinh vẻ đẹp kín đáo cổ xưa.", "rule_check_status": "PASSED" },
  { id: "OF_11", name: "Uy Nghi Đình Triều - Viên Lĩnh Nam Quan Phục", gender: "Male", applicable_events: ["C03", "C02", "C02"], style: "Court ceremony revival", composition: { inner: "cs_32", "top": null, outer_formal: null, outer_traditional: "V09_1", bottom_pants: "cs_03", bottom_skirt: null, shoes: null, traditional_footwear: "v12_1", headwear: "Mũ Phốc Đầu", jewelry: ["j19"], other_accessories: ["Đai lưng to bản viền kim loại", "Hốt ngà cầm tay"] }, color_palette: { primary: "#800020", secondary: "#111111", accent: "#D4AF37" }, styling_notes: "Áo Viên Lĩnh cổ tròn thụng khép nút vai phải uy nghiêm, kết hợp quần tây đứng dáng và hài cung đình nam trang trọng, tái hiện sinh động khí chất quan trường tôn ti thời phong kiến thịnh trị.", traditional_focus: "Áo Viên Lĩnh nam phẩm phục cung đình mang trật tự tôn nghiêm của nền văn hiến Đại Việt.", "rule_check_status": "PASSED" },
  { id: "OF_12", name: "Viên Lĩnh Quý Nương - Phẩm Cách Cung Vi", gender: "Female", applicable_events: ["C02", "C02", "C02"], style: "Regal dynastic elegance", composition: { inner: "cs_32", "top": null, outer_formal: null, outer_traditional: "V09_2", bottom_pants: "cs_04", bottom_skirt: null, shoes: null, traditional_footwear: "v12_2", headwear: "h01_2", jewelry: ["j05", "j15"], other_accessories: ["Quạt lông vũ cầm tay"] }, color_palette: { primary: "#1E3F66", secondary: "#F3E5AB", accent: "#52B788" }, styling_notes: "Áo Viên Lĩnh nữ cổ tròn cao kín đáo may gấm dệt chìm sang trọng, phối cùng quần culottes lụa thanh thoát, hài cung đình nữ đế thấp và khăn vấn đen nền nã, toát lên phong thái khuê các quý tộc xưa.", traditional_focus: "Áo Viên Lĩnh nữ trang phục cổ điển trang nghiêm của phụ nữ quý tộc thời Lý - Trần - Lê.", "rule_check_status": "PASSED" },
  { id: "OF_13", name: "Duyên Dáng Miền Tây - Bà Ba Sông Nước", gender: "Female", applicable_events: ["C02", "C01", "C06"], style: "Mekong Delta folk charm", composition: { inner: "cs_12", "top": "V04_2", outer_formal: null, outer_traditional: null, bottom_pants: "cs_04", bottom_skirt: null, shoes: "cs_35", traditional_footwear: null, headwear: "h02", jewelry: ["j03"], other_accessories: ["Nón lá thắt quai lụa"] }, color_palette: { primary: "#7FB069", secondary: "#1A1A1A", accent: "#E6AA68" }, styling_notes: "Áo bà ba nữ vải lụa xanh non may xẻ tà ôm nhẹ vóc dáng, kết hợp áo hai dây lót trong kín đáo, quần lụa đen rủ mềm mại, khăn rằn quấn cổ và guốc mộc cao gót mộc mạc mà duyên dáng.", traditional_focus: "Áo bà ba nữ gắn liền khăn rằn tôn vinh vẻ đẹp chân phương, hồn hậu của người phụ nữ Nam Bộ.", "rule_check_status": "PASSED" },
  { id: "OF_14", name: "Chàng Trai Nam Bộ - Bà Ba Mộc Mạc", gender: "Male", applicable_events: ["C02", "C01", "C02"], style: "Rustic southern comfort", composition: { inner: null, "top": "V04_1", outer_formal: null, outer_traditional: null, bottom_pants: "cs_20", bottom_skirt: null, shoes: null, traditional_footwear: "v13", headwear: "h02", jewelry: [], other_accessories: ["Túi đay mộc quai thô"] }, color_palette: { primary: "#4A3525", secondary: "#D7C4B7", accent: "#2C3E50" }, styling_notes: "Áo bà ba nam màu nâu sồng chất phác với túi vuông phía trước kết hợp quần linen suông thoáng mát, khăn rằn vắt vai phong trần và guốc mộc truyền thống, toát lên tinh thần hào sảng sông nước.", traditional_focus: "Áo bà ba nam cùng khăn rằn đại diện cho lối sống giản dị, phóng khoáng của miệt vườn phương Nam.", "rule_check_status": "PASSED" },
  { id: "OF_15", name: "Nắng Hè Cổ Điển - Đối Khâm Đương Đại", gender: "Female", applicable_events: ["C01", "C02", "C06"], style: "Bohemian Oriental modern", composition: { inner: "cs_27", "top": null, outer_formal: "V10", outer_traditional: null, bottom_pants: "cs_20", bottom_skirt: null, shoes: "cs_34", traditional_footwear: null, headwear: null, jewelry: ["j07", "j16"], other_accessories: ["Túi xách mây tre đan thủ công"] }, color_palette: { primary: "#D35400", secondary: "#EAECEE", accent: "#A04000" }, styling_notes: "Áo Đối Khâm khoác buông tơ lụa mỏng nhẹ phối cùng áo quây dệt kim ôm sát và quần linen ống rộng cạp cao, bước trên giày mule thời thượng, kiến tạo diện mạo dạo phố phóng khoáng mang hơi thở di sản.", traditional_focus: "Áo Đối Khâm được ứng dụng khéo léo như một chiếc áo khoác kimono/haori phương Đông thời thượng.", "rule_check_status": "PASSED" },
  { id: "OF_16", name: "Ngoại Giao Tinh Giản - Áo Tấc Đương Đại", gender: "Male", applicable_events: ["C03", "C02", "C07"], style: "Contemporary diplomatic minimal", composition: { inner: "cs_11_1", "top": null, outer_formal: null, outer_traditional: "V06", bottom_pants: "cs_03", bottom_skirt: null, shoes: "cs_15", traditional_footwear: null, headwear: null, jewelry: ["j02"], other_accessories: ["Cặp da tài liệu cầm tay tối giản"] }, color_palette: { primary: "#0B1D3A", secondary: "#FFFFFF", accent: "#7F8C8D" }, styling_notes: "Áo Tấc tay thụng xanh thẫm uy nghi kết hợp lớp trong là áo cổ lọ mỏng hiện đại, quần âu phẳng phiu và giày loafer da cao cấp, tạo hình mẫu trang phục ngoại giao văn hóa đĩnh đạc và tinh tế.", traditional_focus: "Áo Tấc giao hòa giữa tính lễ nghi triều đình và ngôn ngữ thời trang nam giới tối giản hiện đại.", "rule_check_status": "PASSED" },
  { id: "OF_17", name: "Năng Động Trẻ Trung - Áo Dài & Denim", gender: "Female", applicable_events: ["C01", "C06", "C02"], style: "Youthful street-style Ao Dai", composition: { inner: null, "top": "V01_2", outer_formal: null, outer_traditional: null, bottom_pants: "cs_01", bottom_skirt: null, shoes: "cs_14", traditional_footwear: null, headwear: null, jewelry: ["j04"], other_accessories: ["Túi tote vải bố vẽ họa tiết hoa sen"] }, color_palette: { primary: "#F1948A", secondary: "#5DADE2", accent: "#FFFFFF" }, styling_notes: "Áo dài tân thời nữ tà lửng cách điệu phối phá cách cùng quần jeans ống rộng và sneaker trắng basic, mang lại tinh thần năng động, tươi mới cho giới trẻ yêu văn hóa truyền thống khi dạo phố cuối tuần.", traditional_focus: "Áo dài tân thời nữ kết hợp phong cách đường phố (streetwear) đầy tự tin và phóng khoáng.", "rule_check_status": "PASSED" },
  { id: "OF_18", name: "Âm Hưởng Bắc Bộ - Tứ Thân Nghệ Thuật", gender: "Female", applicable_events: ["C02", "C02", "C06"], style: "Contemporary folk performance", composition: { inner: "cs_11_2", "top": null, outer_formal: null, outer_traditional: "V02", bottom_pants: null, bottom_skirt: "cs_22", shoes: "cs_35", traditional_footwear: null, headwear: "h01_2", jewelry: ["j01", "j17"], other_accessories: ["Quạt giấy dó vẽ tranh dân gian"] }, color_palette: { primary: "#6C3483", secondary: "#17202A", accent: "#F7DC6F" }, styling_notes: "Áo tứ thân tà lụa màu mận khoác ngoài áo cổ lọ ôm dáng, phối chân váy lụa satin suông bóng mượt, guốc mộc cao gót tôn dáng và kiềng cổ trang trọng, biểu diễn nghệ thuật dân ca đương đại.", traditional_focus: "Áo tứ thân kết hợp khăn vấn gợi nhắc bóng dáng liền chị quan họ trong diện mạo sân khấu hiện đại.", "rule_check_status": "PASSED" },
  { id: "OF_19", name: "Bản Lĩnh Thời Thượng - Ngũ Thân Nam & Boots", gender: "Male", applicable_events: ["C02", "C03", "C06"], style: "Editorial avant-garde traditional", composition: { inner: "cs_11_1", "top": null, outer_formal: null, outer_traditional: "V05_1", bottom_pants: "cs_03", bottom_skirt: null, shoes: "cs_36", traditional_footwear: null, headwear: "h01_1", jewelry: ["j15"], other_accessories: ["Khăn lụa gài túi áo cổ điển"] }, color_palette: { primary: "#17202A", secondary: "#2C3E50", accent: "#F39C12" }, styling_notes: "Áo ngũ thân tay chẽn nam dệt gấm đen tuyền khoác ngoài áo cổ lọ ôm sát, kết hợp quần tây may đo và bốt da lì cổ thấp, hoàn thiện bởi khăn vấn đen và nhẫn vàng tạo hình ảnh thời trang tạp chí sắc lạnh.", traditional_focus: "Áo ngũ thân tay chẽn nam phô diễn nét quyền uy, đĩnh đạc qua lăng kính thời trang tiên phong.", "rule_check_status": "PASSED" },
  { id: "OF_20", name: "Thiền Ý Tĩnh Tại - Đối Khâm Phi Giới Tính", gender: "Unisex", applicable_events: ["C02", "C02", "C01"], style: "Genderless Zen aesthetic", composition: { inner: "cs_11_1", "top": null, outer_formal: "V10", outer_traditional: null, bottom_pants: "cs_04", bottom_skirt: null, shoes: "cs_14", traditional_footwear: null, headwear: null, jewelry: ["j02", "j05"], other_accessories: ["Khăn choàng đũi tơ tằm thô mộc"] }, color_palette: { primary: "#7D6608", secondary: "#EAEDED", accent: "#5D6D7E" }, styling_notes: "Áo Đối Khâm vải đũi nhuộm màu tự nhiên phom suông rộng khoác ngoài áo cổ lọ trung tính, phối quần culottes đũi bồng bềnh và sneaker trắng tối giản, điểm chuỗi hạt gỗ và vòng cẩm thạch đậm chất thiền định.", traditional_focus: "Áo Đối Khâm dáng vạt song song buông rủ mang lại cảm giác thanh thản, tự do không giới hạn định kiến giới tính.", "rule_check_status": "PASSED" }
];

// DỮ LIỆU PHỤ KIỆN (MŨ NÓN & TRANG SỨC)
export const ACCESSORIES: AccessoryItem[] = [
  {
    id: "j01",
    name: "Kiềng cổ",
    origin: "Kiềng cổ là loại trang sức dạng vòng cứng đeo quanh cổ, có lịch sử lâu đời trong trang phục truyền thống của phụ nữ Việt Nam. Kiềng có thể được chế tác từ bạc, vàng hoặc các kim loại khác và từng xuất hiện trong trang phục của phụ nữ ở nhiều vùng miền.",
    characteristics: "Vòng cổ có cấu trúc cứng hoặc bán cứng, thường có dạng tròn hoặc hơi cong theo cổ. Một số loại có mặt trang trí, hoa văn chạm khắc hoặc các chi tiết ở phần giữa.",
    usage_context: "Trang phục truyền thống, lễ hội, cưới hỏi, dịp lễ Tết và các hoạt động tái hiện văn hóa.",
    colors: ["Bạc", "Vàng", "Vàng ánh đỏ", "Màu kim loại tự nhiên"],
    accessories: ["Áo dài", "Áo ngũ thân", "Áo tứ thân", "Áo bà ba"],
    significance: "Thể hiện sự chỉn chu, duyên dáng và giá trị thẩm mỹ của trang phục; trong một số cộng đồng, trang sức còn phản ánh điều kiện kinh tế và địa vị xã hội.",
    notes: "Nên chọn kích thước và kiểu dáng phù hợp với cổ áo. Không nên mặc kiềng quá lớn với những trang phục có cổ hoặc hoa văn cầu kỳ.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Tư liệu về trang sức truyền thống Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Formal",
    image_url: ["assets/jewelry/j01.png"]
  },
  {
    id: "j02",
    name: "Vòng cổ chuỗi hạt",
    origin: "Vòng cổ chuỗi hạt phát triển từ tập quán sử dụng hạt tự nhiên như đá, gỗ, ngọc, thủy tinh hoặc hạt kim loại để làm đồ trang sức. Các dạng chuỗi hạt xuất hiện trong nhiều cộng đồng và truyền thống văn hóa ở Việt Nam.",
    characteristics: "Gồm nhiều hạt được xâu thành một hoặc nhiều vòng, có thể có mặt dây chuyền ở giữa. Kích thước và chất liệu hạt đa dạng.",
    usage_context: "Trang phục thường ngày, lễ hội, trang phục truyền thống, cưới hỏi và các dịp trang trọng.",
    colors: ["Đỏ", "Trắng", "Đen", "Nâu", "Xanh", "Vàng", "Màu tự nhiên"],
    accessories: ["Áo dài", "Áo ngũ thân", "Áo tứ thân"],
    significance: "Chủ yếu mang giá trị thẩm mỹ; tùy chất liệu, một số người còn gắn cho chuỗi hạt ý nghĩa tâm linh hoặc phong thủy.",
    notes: "Ý nghĩa phong thủy của màu sắc hoặc loại đá là quan niệm tín ngưỡng, không phải đặc tính khoa học đã được chứng minh.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Tư liệu về trang sức và thủ công truyền thống Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Smart-casual",
    image_url: ["assets/jewelry/j02.png"]
  },
  {
    id: "j03",
    name: "Vòng tay chuỗi hạt",
    origin: "Vòng tay chuỗi hạt là dạng trang sức phổ biến được tạo từ nhiều hạt xâu liên tiếp. Chất liệu có thể là gỗ, đá, ngọc, thủy tinh hoặc kim loại.",
    characteristics: "Dạng chuỗi nhiều hạt tạo thành vòng quanh cổ tay; có thể sử dụng một loại hạt đồng nhất hoặc phối nhiều màu và kích thước.",
    usage_context: "Đời sống thường ngày, lễ hội, sự kiện văn hóa và phối cùng trang phục truyền thống hoặc hiện đại.",
    colors: ["Nâu", "Đen", "Trắng", "Đỏ", "Xanh", "Vàng"],
    accessories: ["Vòng cổ", "Nhẫn", "Hoa tai", "Áo dài"],
    significance: "Tạo điểm nhấn cho cổ tay và hoàn thiện tổng thể trang phục; một số loại được sử dụng với ý nghĩa tâm linh hoặc phong thủy theo quan niệm cá nhân.",
    notes: "Không nên phối quá nhiều vòng hạt lớn cùng lúc với trang phục đã có nhiều họa tiết.",
    references: ["Tư liệu về trang sức truyền thống và thủ công mỹ nghệ Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Casual",
    image_url: ["assets/jewelry/j03.png"]
  },
  {
    id: "j04",
    name: "Vòng đá phong thủy",
    origin: "Vòng đá phong thủy là nhóm trang sức hiện đại sử dụng các loại đá tự nhiên hoặc vật liệu được gọi là đá phong thủy. Khái niệm này chịu ảnh hưởng từ các hệ thống tín ngưỡng và văn hóa Đông Á và hiện được sử dụng phổ biến trong thị trường trang sức hiện đại.",
    characteristics: "Thường gồm các hạt đá tròn được xâu thành vòng; một số mẫu sử dụng hạt chạm khắc hoặc kết hợp với charm.",
    usage_context: "Đời sống thường ngày, thời trang, quà tặng và các dịp mang tính cá nhân.",
    colors: ["Đen", "Đỏ", "Xanh lá", "Xanh dương", "Trắng", "Vàng", "Tím"],
    accessories: ["Áo dài", "Trang phục hiện đại", "Trang phục truyền thống"],
    significance: "Theo quan niệm phong thủy, màu sắc và loại đá có thể được gắn với may mắn, bình an hoặc tài lộc; đây là niềm tin văn hóa, không phải kết luận khoa học.",
    notes: "Không nên mô tả tác dụng phong thủy như công dụng y khoa hoặc khả năng chữa bệnh.",
    references: ["Tư liệu về văn hóa tín ngưỡng Đông Á", "Tài liệu về trang sức đá phong thủy"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Casual",
    image_url: ["assets/jewelry/j04.png"]
  },
  {
    id: "j05",
    name: "Vòng cẩm thạch",
    origin: "Vòng cẩm thạch thuộc nhóm trang sức ngọc được sử dụng rộng rãi ở Đông Á và du nhập, giao lưu trong văn hóa Việt Nam. Cẩm thạch thường được chế tác thành vòng liền khối hoặc vòng bản rộng.",
    characteristics: "Vòng thường được mài thành hình tròn, bề mặt nhẵn bóng, có thể trong mờ hoặc bán trong. Màu sắc và vân đá thay đổi tùy chất liệu.",
    usage_context: "Trang sức thường ngày, lễ Tết, sự kiện trang trọng và làm quà tặng.",
    colors: ["Xanh lục", "Trắng", "Xanh nhạt", "Tím", "Vàng", "Nhiều màu pha vân"],
    accessories: ["Áo dài", "Áo ngũ thân", "Trang sức ngọc"],
    significance: "Trong văn hóa Đông Á, ngọc thường gắn với sự quý giá, thanh khiết và phẩm chất tốt đẹp. Một số người cũng xem cẩm thạch là vật mang may mắn.",
    notes: "Cần phân biệt cẩm thạch với các loại đá màu xanh khác; không nên mặc định mọi vòng màu xanh đều là cẩm thạch.",
    references: ["Tư liệu về ngọc và trang sức Đông Á", "Tư liệu về trang sức truyền thống Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Formal",
    image_url: ["assets/jewelry/j05.png"]
  },
  {
    id: "j06",
    name: "Vòng ngọc bích",
    origin: "Ngọc bích là loại ngọc được sử dụng lâu đời trong văn hóa Đông Á và xuất hiện trong trang sức của Việt Nam thông qua giao lưu văn hóa và thương mại.",
    characteristics: "Thường được chế tác thành vòng tròn liền khối, bề mặt mài bóng; có thể có độ trong và sắc xanh khác nhau.",
    usage_context: "Trang sức thường ngày, lễ hội, cưới hỏi và các dịp trang trọng.",
    colors: ["Xanh lục đậm", "Xanh lục nhạt", "Xanh trắng", "Xanh pha vân"],
    accessories: ["Áo dài", "Áo ngũ thân", "Trang sức ngọc"],
    significance: "Ngọc bích thường được gắn với vẻ đẹp thanh nhã, sự bền bỉ và giá trị quý trọng; các ý nghĩa phong thủy là quan niệm văn hóa.",
    notes: "Không nên khẳng định màu hoặc loại ngọc quyết định vận mệnh hay sức khỏe của người đeo.",
    references: ["Tư liệu về ngọc trong văn hóa Đông Á", "Tư liệu về trang sức truyền thống Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Formal",
    image_url: ["assets/jewelry/j06.png"]
  },
  {
    id: "j07",
    name: "Vòng mã não",
    origin: "Mã não là một dạng chalcedony được sử dụng làm đồ trang sức từ lâu đời ở nhiều nền văn hóa. Tại Việt Nam, vòng mã não hiện phổ biến chủ yếu dưới dạng trang sức và vật phẩm mang quan niệm phong thủy.",
    characteristics: "Có dạng vòng hạt hoặc vòng liền khối; bề mặt bóng, thường xuất hiện các dải màu hoặc vân tự nhiên.",
    usage_context: "Trang sức thường ngày, quà tặng, lễ hội và các dịp trang trọng.",
    colors: ["Đỏ", "Cam", "Nâu", "Trắng", "Đen", "Vàng", "Xanh", "Nhiều màu pha vân"],
    accessories: ["Vòng cổ chuỗi hạt", "Nhẫn", "Áo dài"],
    significance: "Giá trị chính là thẩm mỹ; trong quan niệm phong thủy, mã não thường được gắn với bình an và may mắn.",
    notes: "Màu sắc và vân đá là đặc điểm tự nhiên, không nên dùng ý nghĩa phong thủy như một đặc tính khoa học.",
    references: ["Tài liệu khoáng vật học về mã não", "Tư liệu về trang sức đá trong văn hóa Đông Á"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Casual",
    image_url: ["assets/jewelry/j07.png"]
  },
  {
    id: "j08",
    name: "Bộ diêu",
    origin: "Bộ diêu, hay bộ dao/bộ diêu, thuộc nhóm trang sức tóc dạng có phần tua hoặc vật trang trí chuyển động khi người đeo di chuyển. Khái niệm này có nguồn gốc rõ nét trong truyền thống trang sức Đông Á, đặc biệt là Trung Hoa, hơn là một loại trang sức Việt Nam đặc trưng.",
    characteristics: "Gồm phần cài vào búi tóc và các chi tiết treo, thường là dây, hạt, hoa hoặc kim loại tạo chuyển động.",
    usage_context: "Phục dựng cổ trang, biểu diễn, sân khấu, chụp ảnh và các concept lấy cảm hứng Đông Á.",
    colors: ["Vàng", "Bạc", "Đỏ", "Xanh", "Trắng", "Ngọc bích", "Phối nhiều màu"],
    accessories: ["Kiểu tóc búi", "Trang phục lễ nghi", "Trang phục cổ trang"],
    significance: "Tạo vẻ cầu kỳ, sang trọng và chuyển động cho kiểu tóc.",
    notes: "Không nên gắn bộ diêu mặc định với áo dài, áo ngũ thân hoặc các trang phục Việt Nam nếu hệ thống yêu cầu tính chính xác văn hóa.",
    references: ["Tư liệu về trang sức tóc Đông Á", "Tư liệu lịch sử trang phục Trung Hoa"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Formal",
    image_url: ["assets/jewelry/j08.png"]
  },
  {
    id: "j09",
    name: "Lưu tô",
    origin: "Lưu tô là dạng chi tiết trang trí dạng tua rủ, xuất hiện trong nhiều truyền thống trang sức và phục sức Đông Á. Trong trang sức tóc, lưu tô thường được kết hợp với trâm, bộ diêu hoặc các phụ kiện cài tóc.",
    characteristics: "Gồm các sợi dây, chuỗi hạt hoặc vật trang trí nhỏ tạo thành tua dài rủ xuống.",
    usage_context: "Trang sức tóc, phục trang lễ nghi, sân khấu, chụp ảnh cổ trang và các concept truyền thống.",
    colors: ["Vàng", "Bạc", "Đỏ", "Xanh", "Trắng", "Đen", "Phối nhiều màu"],
    accessories: ["Trâm", "Bộ diêu", "Hoa cài tóc"],
    significance: "Tạo chuyển động và điểm nhấn cho khuôn mặt, mái tóc; đồng thời tăng cảm giác trang trọng.",
    notes: "Lưu tô không phải một loại trang sức độc lập cố định mà thường là chi tiết trang trí của một món phụ kiện lớn hơn.",
    references: ["Tư liệu về trang sức tóc Đông Á", "Tư liệu về phục sức Đông Á"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Formal",
    image_url: ["assets/jewelry/j09.png"]
  },
  {
    id: "j10",
    name: "Trâm phượng",
    origin: "Trâm phượng là loại trâm cài tóc lấy hình tượng chim phượng làm mô-típ trang trí. Hình tượng phượng xuất hiện rộng rãi trong mỹ thuật Đông Á và từng được sử dụng trong trang phục, trang sức của tầng lớp quý tộc và cung đình.",
    characteristics: "Thân trâm dùng để cố định tóc, phần đầu trâm tạo hình chim phượng; có thể kết hợp hoa văn, ngọc, đá hoặc tua rủ.",
    usage_context: "Lễ nghi, cưới hỏi, phục dựng cổ phục, sân khấu và chụp ảnh.",
    colors: ["Vàng", "Bạc", "Đỏ", "Xanh", "Trắng", "Đen"],
    accessories: ["Kiểu tóc búi", "Lưu tô", "Bộ diêu", "Trang phục lễ nghi"],
    significance: "Phượng thường được sử dụng như biểu tượng của vẻ đẹp, cao quý và sự trang trọng trong mỹ thuật Đông Á.",
    notes: "Khi đưa vào data Việt phục cần xác định kiểu trâm và bối cảnh lịch sử cụ thể, tránh đồng nhất mô-típ phượng với một quy chế cung đình Việt Nam cụ thể nếu không có tư liệu.",
    references: ["Ngàn năm áo mũ – Trần Quang Đức", "Tư liệu về mỹ thuật và trang sức cung đình Đông Á"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Formal",
    image_url: ["assets/jewelry/j10.png"]
  },
  {
    id: "j11",
    name: "Trâm hoa",
    origin: "Trâm hoa là nhóm trâm cài tóc có phần đầu được tạo hình hoa hoặc gắn hoa trang trí. Việc dùng hoa làm mô-típ trang sức tóc phổ biến trong nhiều truyền thống văn hóa châu Á, trong đó có Việt Nam.",
    characteristics: "Thân trâm dài để xuyên qua búi tóc; đầu trâm tạo hình hoa, có thể làm bằng kim loại, gỗ, ngọc, đá hoặc vật liệu tổng hợp.",
    usage_context: "Trang phục truyền thống, lễ hội, cưới hỏi, biểu diễn và chụp ảnh.",
    colors: ["Trắng", "Đỏ", "Hồng", "Vàng", "Xanh", "Bạc"],
    accessories: ["Khăn vấn", "Tóc búi", "Áo dài", "Trang phục cổ truyền"],
    significance: "Hoa tượng trưng cho vẻ đẹp, sự thanh nhã và nữ tính; ý nghĩa cụ thể thay đổi theo loại hoa.",
    notes: "Nên chọn kiểu hoa phù hợp với trang phục và bối cảnh; không nên sử dụng các mẫu quá cầu kỳ nếu outfit mang tính dân gian giản dị.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Tư liệu về trang sức tóc truyền thống"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Formal",
    image_url: ["assets/jewelry/j11_a.png", "assets/jewelry/j11_b.png"]
  },
  {
    id: "j12",
    name: "Khuyên tai đá phong thủy",
    origin: "Khuyên tai đá phong thủy là dạng trang sức hiện đại sử dụng đá tự nhiên hoặc đá được thương mại hóa dưới tên gọi đá phong thủy.",
    characteristics: "Có thể là dạng móc, đinh hoặc vòng; phần trang trí sử dụng một hoặc nhiều viên đá.",
    usage_context: "Đời sống thường ngày, lễ hội, thời trang và các dịp trang trọng.",
    colors: ["Đỏ", "Xanh", "Trắng", "Tím", "Vàng", "Đen"],
    accessories: ["Vòng đá", "Vòng ngọc", "Nhẫn", "Áo dài"],
    significance: "Mang giá trị thẩm mỹ; một số người tin rằng loại đá và màu sắc mang ý nghĩa phong thủy.",
    notes: "Không mô tả đá phong thủy như có khả năng chữa bệnh hoặc tác động chắc chắn đến vận mệnh.",
    references: ["Tư liệu về trang sức đá", "Tư liệu về văn hóa phong thủy Đông Á"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Smart-casual",
    image_url: ["assets/jewelry/j12_a.png", "assets/jewelry/j12_b.png"]
  },
  {
    id: "j13",
    name: "Khuyên tai phượng hoàng",
    origin: "Khuyên tai phượng hoàng sử dụng hình tượng chim phượng hoàng làm mô-típ trang trí. Hình tượng phượng có vị trí quan trọng trong mỹ thuật và biểu tượng Đông Á, đồng thời cũng xuất hiện trong nghệ thuật cung đình Việt Nam.",
    characteristics: "Có thể tạo hình trực tiếp chim phượng hoặc sử dụng đầu, cánh và đuôi phượng làm hoa văn.",
    usage_context: "Lễ hội, cưới hỏi, chụp ảnh cổ phục, sân khấu và trang phục có tính lễ nghi.",
    colors: ["Vàng", "Đỏ", "Xanh", "Bạc", "Đen", "Đa màu"],
    accessories: ["Trâm phượng", "Áo dài", "Áo Nhật Bình", "Trang phục lễ nghi"],
    significance: "Gợi sự cao quý, vẻ đẹp, may mắn và tính trang trọng trong biểu tượng Đông Á.",
    notes: "Cần phân biệt mô-típ phượng trong mỹ thuật Việt Nam với các thiết kế phượng mang phong cách cổ trang Trung Hoa hiện đại.",
    references: ["Ngàn năm áo mũ – Trần Quang Đức", "Tư liệu mỹ thuật cung đình Việt Nam và Đông Á"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Formal",
    image_url: ["assets/jewelry/j13.png"]
  },
  {
    id: "j14",
    name: "Khuyên tai bạc nạm đá quý",
    origin: "Khuyên tai bạc nạm đá quý thuộc nhóm trang sức kim loại kết hợp đá trang trí. Bạc và đá quý đã được sử dụng trong nhiều truyền thống trang sức tại Việt Nam và khu vực Đông Nam Á.",
    characteristics: "Thân khuyên bằng bạc, phần mặt hoặc thân được gắn một hoặc nhiều viên đá.",
    usage_context: "Trang phục lễ hội, cưới hỏi, sự kiện trang trọng hoặc đời sống thường ngày.",
    colors: ["Bạc", "Đỏ", "Xanh", "Trắng", "Tím", "Vàng"],
    accessories: ["Kiềng bạc", "Vòng tay", "Nhẫn bạc", "Áo dài"],
    significance: "Thể hiện sự tinh tế, giá trị vật liệu và địa vị kinh tế trong một số bối cảnh.",
    notes: "Nếu cần độ chính xác vật liệu, nên xác định cụ thể loại đá thay vì chỉ sử dụng tên gọi thương mại 'đá quý'.",
    references: ["Tư liệu về nghề kim hoàn và trang sức bạc Việt Nam", "Trang phục Việt Nam – Đoàn Thị Tình"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Formal",
    image_url: ["assets/jewelry/j14.png"]
  },
  {
    id: "j15",
    name: "Nhẫn vàng",
    origin: "Nhẫn vàng là dạng trang sức phổ biến trong đời sống Việt Nam, được chế tác từ vàng với nhiều kiểu dáng khác nhau. Vàng có giá trị kinh tế và thường được sử dụng trong trang sức cũng như quà tặng.",
    characteristics: "Dạng vòng kim loại nhỏ đeo ở ngón tay; có thể trơn hoặc gắn đá, chạm hoa văn.",
    usage_context: "Đời sống thường ngày, cưới hỏi, lễ Tết, sự kiện và làm quà tặng.",
    colors: ["Vàng vàng", "Vàng trắng", "Vàng hồng"],
    accessories: ["Vòng tay", "Kiềng", "Hoa tai", "Áo dài"],
    significance: "Vừa có giá trị trang sức vừa có giá trị vật chất; trong cưới hỏi, nhẫn vàng còn gắn với nghi thức trao tặng và cam kết hôn nhân.",
    notes: "Kiểu nhẫn cần phù hợp với bối cảnh; nhẫn cưới không nên được sử dụng như một chi tiết mặc định cho mọi outfit truyền thống.",
    references: ["Tư liệu về văn hóa cưới hỏi Việt Nam", "Tư liệu về nghề kim hoàn Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Formal",
    image_url: ["assets/jewelry/j15.png"]
  },
  {
    id: "j16",
    name: "Nhẫn mã não",
    origin: "Nhẫn mã não sử dụng mã não làm đá trang trí hoặc mặt nhẫn. Mã não là vật liệu đá bán quý được sử dụng rộng rãi trong chế tác trang sức.",
    characteristics: "Thường có mặt đá mã não được mài nhẵn hoặc chạm khắc, gắn trên thân nhẫn bằng bạc, vàng hoặc kim loại khác.",
    usage_context: "Trang sức thường ngày, quà tặng, lễ hội và các dịp trang trọng.",
    colors: ["Đỏ", "Cam", "Nâu", "Trắng", "Đen", "Xanh", "Màu pha vân"],
    accessories: ["Vòng mã não", "Vòng đá", "Trang phục truyền thống", "Trang phục hiện đại"],
    significance: "Có giá trị thẩm mỹ; trong quan niệm phong thủy, mã não thường được gắn với bình an và may mắn.",
    notes: "Không nên trình bày ý nghĩa phong thủy như tác dụng đã được khoa học chứng minh.",
    references: ["Tài liệu khoáng vật học về mã não", "Tư liệu về trang sức đá"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Smart-casual",
    image_url: ["assets/jewelry/j16.png"]
  },
  {
    id: "j17",
    name: "Vòng cổ ngọc trai",
    origin: "Ngọc trai là vật liệu trang sức có lịch sử lâu đời ở nhiều nền văn hóa ven biển. Việt Nam có truyền thống khai thác và nuôi trai lấy ngọc, đồng thời ngọc trai được sử dụng rộng rãi trong trang sức hiện đại.",
    characteristics: "Gồm một hoặc nhiều chuỗi ngọc trai xâu liên tiếp; có thể kết hợp với mặt dây chuyền hoặc kim loại quý.",
    usage_context: "Áo dài, cưới hỏi, lễ Tết, sự kiện trang trọng, công sở và thời trang.",
    colors: ["Trắng", "Kem", "Hồng", "Vàng", "Bạc ánh", "Đen"],
    accessories: ["Áo dài", "Khuyên tai ngọc trai", "Nhẫn", "Trang sức đơn giản"],
    significance: "Gợi sự thanh lịch, trang nhã và sang trọng.",
    notes: "Ngọc trai khá mềm so với nhiều loại đá trang sức nên cần tránh va đập, hóa chất và nước hoa trực tiếp.",
    references: ["Tư liệu về nghề nuôi trai và ngọc trai Việt Nam", "Tư liệu về trang sức Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Formal",
    image_url: ["assets/jewelry/j17.png"]
  },
  {
    id: "j18",
    name: "Khuyên tai ngọc trai",
    origin: "Khuyên tai ngọc trai phát triển từ việc sử dụng ngọc trai làm vật liệu trang sức, đặc biệt phổ biến trong trang sức nữ hiện đại và các bộ trang sức mang tính trang trọng.",
    characteristics: "Thường là dạng đinh, móc hoặc vòng có gắn một hoặc nhiều viên ngọc trai.",
    usage_context: "Áo dài, cưới hỏi, lễ Tết, công sở, sự kiện và trang phục trang trọng.",
    colors: ["Trắng", "Kem", "Hồng", "Vàng", "Xám", "Đen"],
    accessories: ["Vòng cổ ngọc trai", "Vòng tay", "Nhẫn vàng", "Áo dài"],
    significance: "Tạo vẻ thanh lịch, nhẹ nhàng và trang trọng.",
    notes: "Nên phối kích thước ngọc trai với kiểu cổ áo; khuyên quá lớn có thể làm tổng thể nặng nề.",
    references: ["Tư liệu về ngọc trai và trang sức Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "female",
    formality: "Formal",
    image_url: ["assets/jewelry/j18.png"]
  },
  {
    id: "j19",
    name: "Ngọc bội",
    origin: "Ngọc bội là dạng vật phẩm bằng ngọc được đeo hoặc treo trên trang phục, có lịch sử lâu đời trong văn hóa Đông Á. Trong lịch sử Việt Nam, đồ ngọc và các dạng phụ kiện đeo bên người cũng xuất hiện trong tầng lớp quý tộc và môi trường cung đình, nhưng nhiều hình thức ngọc bội hiện đại chịu ảnh hưởng mạnh từ mỹ thuật Đông Á.",
    characteristics: "Thường là miếng ngọc được chạm khắc thành hình tròn, vuông, hồ lô, cá, chim, hoa hoặc các biểu tượng khác; có dây hoặc tua để treo.",
    usage_context: "Trang phục lễ nghi, cổ phục, phục dựng lịch sử, sân khấu và các concept truyền thống.",
    colors: ["Trắng", "Xanh ngọc", "Xanh lục", "Vàng", "Nâu", "Đen"],
    accessories: ["Thắt lưng", "Đai", "Tua rủ", "Trang phục cổ truyền"],
    significance: "Ngọc thường được gắn với sự quý giá, thanh khiết và phẩm chất tốt đẹp; hình dạng cụ thể có thể mang các ý nghĩa biểu tượng khác nhau.",
    notes: "Không nên mặc định ngọc bội là phụ kiện của mọi loại Việt phục. Cần kiểm tra kiểu dáng, thời kỳ và bối cảnh trước khi phối với áo ngũ thân, áo tấc, áo Nhật Bình hoặc các trang phục khác.",
    references: ["Ngàn năm áo mũ – Trần Quang Đức", "Tư liệu về ngọc trong văn hóa Đông Á và Việt Nam"],
    type: "jewelry",
    category: "jewelry",
    gender: "unisex",
    formality: "Formal",
    image_url: ["assets/jewelry/j19.png"]
  },
  {
    id: "h01_1",
    name: "Khăn vấn",
    origin: "Khăn vấn là kiểu khăn đội đầu truyền thống của người Việt, đặc biệt gắn với hình ảnh trang phục cổ truyền ở Bắc Bộ. Khăn được quấn quanh tóc thành nhiều vòng, tạo thành dáng búi hoặc vành khăn đặc trưng.",
    characteristics: "Là một dải vải dài được quấn nhiều vòng quanh đầu và tóc, tạo thành khối tròn hoặc hơi dẹt. Cách vấn có thể thay đổi tùy vùng miền, thời kỳ và kiểu trang phục. Khăn ôm gọn phần tóc và tạo hình dáng cân đối cho khuôn mặt.",
    usage_context: "Trang phục truyền thống Bắc Bộ, lễ hội dân gian, biểu diễn nghệ thuật, chụp ảnh cổ phục và các sự kiện văn hóa. Có thể kết hợp với các trang phục truyền thống phù hợp với từng bối cảnh lịch sử.",
    colors: ["Đen", "Nâu", "Xanh sẫm", "Các màu tối"],
    accessories: ["Áo ngũ thân", "Trang phục truyền thống Bắc Bộ", "Thắt lưng", "Trang sức truyền thống đơn giản"],
    significance: "Góp phần tạo nên hình ảnh người Việt trong trang phục truyền thống với vẻ kín đáo, nền nã và cân đối; đồng thời thể hiện kỹ thuật tạo kiểu tóc và khăn đội đầu truyền thống.",
    notes: "Không nên dùng khăn vấn như phụ kiện mặc định cho mọi loại Việt phục. Kiểu vấn cần phù hợp với thời kỳ, vùng miền, giới tính và loại trang phục. Khi phục dựng lịch sử cần phân biệt cách vấn tóc và khăn đội đầu giữa các giai đoạn.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Ngàn năm áo mũ – Trần Quang Đức", "Tư liệu về trang phục phụ nữ Bắc Bộ và văn hóa dân gian Việt Nam"],
    type: "headwear",
    category: "headwear",
    gender: "male",
    formality: "Formal",
    image_url: "assets/headwear/h01_1.png"
  },
  {
    id: "h01_2",
    name: "Khăn vấn",
    origin: "Khăn vấn là kiểu khăn đội đầu truyền thống của phụ nữ Việt Nam, đặc biệt gắn với hình ảnh phụ nữ Bắc Bộ trong trang phục cổ truyền. Khăn được quấn quanh tóc thành nhiều vòng, tạo thành dáng búi hoặc vành khăn đặc trưng.",
    characteristics: "Là một dải vải dài được quấn nhiều vòng quanh đầu và tóc, tạo thành khối tròn hoặc hơi dẹt. Cách vấn có thể thay đổi tùy vùng miền, thời kỳ và kiểu trang phục. Khăn thường ôm gọn phần tóc, tạo vẻ nền nã và cân đối cho khuôn mặt.",
    usage_context: "Trang phục truyền thống Bắc Bộ, lễ hội dân gian, hội làng, biểu diễn nghệ thuật, chụp ảnh cổ phục và các sự kiện văn hóa. Đặc biệt phù hợp với các concept trang phục nữ Bắc Bộ.",
    colors: ["Đen", "Nâu", "Xanh sẫm", "Các màu tối"],
    accessories: ["Áo tứ thân", "Áo yếm", "Áo ngũ thân", "Thắt lưng màu", "Váy", "Hoa tai", "Vòng cổ"],
    significance: "Tạo nên hình ảnh người phụ nữ Việt Nam truyền thống với vẻ kín đáo, nền nã và duyên dáng. Khăn vấn cũng góp phần nhận diện phong cách trang phục dân gian Bắc Bộ.",
    notes: "Không nên dùng khăn vấn như phụ kiện mặc định cho mọi loại Việt phục. Kiểu vấn phù hợp nhất với trang phục nữ Bắc Bộ và các concept dân gian, đặc biệt là áo tứ thân. Với áo dài hiện đại hoặc trang phục Nam Bộ cần cân nhắc bối cảnh trước khi phối.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Ngàn năm áo mũ – Trần Quang Đức", "Tư liệu về trang phục phụ nữ Bắc Bộ và văn hóa dân gian Việt Nam"],
    type: "headwear",
    category: "headwear",
    gender: "female",
    formality: "Formal",
    image_url: "assets/headwear/h01_2.png"
  },
  {
    id: "h02",
    name: "Khăn rằn",
    origin: "Khăn rằn là loại khăn đặc trưng của vùng Nam Bộ, đặc biệt gắn với hình ảnh người dân miền Tây Nam Bộ. Khăn có mối liên hệ với văn hóa Khmer Nam Bộ và quá trình giao lưu văn hóa tại khu vực đồng bằng sông Cửu Long. Qua thời gian, khăn rằn trở thành một biểu tượng quen thuộc của đời sống và văn hóa Nam Bộ.",
    characteristics: "Là một dải khăn hình chữ nhật dài, thường được dệt với các ô caro hoặc đường sọc đan xen. Khăn có kích thước tương đối gọn, có thể quàng quanh cổ, vắt trên vai hoặc sử dụng trong sinh hoạt.",
    usage_context: "Lao động và sinh hoạt thường ngày ở Nam Bộ, đi đồng, đi ruộng, đi ghe và hoạt động ngoài trời. Ngày nay còn được sử dụng trong lễ hội, biểu diễn nghệ thuật, hoạt động văn hóa và các concept thời trang lấy cảm hứng Nam Bộ.",
    colors: ["Đen - trắng", "Đỏ - trắng", "Xanh - trắng", "Các biến thể màu khác"],
    accessories: ["Áo bà ba", "Quần đen", "Quần nâu", "Nón lá", "Trang phục dân gian Nam Bộ"],
    significance: "Gắn với hình ảnh người dân Nam Bộ, đặc biệt là vẻ đẹp giản dị, mộc mạc và gần gũi với đời sống sông nước và lao động. Khăn rằn cũng trở thành một biểu tượng văn hóa quen thuộc của miền Nam.",
    notes: "Khăn rằn có tính nhận diện Nam Bộ khá mạnh, vì vậy không nên dùng làm phụ kiện mặc định cho các outfit Bắc Bộ, Trung Bộ hoặc trang phục cung đình. Khi phối với áo dài hoặc cổ phục khác cần có lý do về bối cảnh.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Tư liệu về văn hóa Nam Bộ và Khmer Nam Bộ", "Các nghiên cứu về trang phục và đời sống dân gian Nam Bộ"],
    type: "headwear",
    category: "headwear",
    gender: "unisex",
    formality: "Casual",
    image_url: "assets/headwear/h02.png"
  },
  {
    id: "h03",
    name: "Nón quai thao",
    origin: "Nón quai thao là loại nón truyền thống gắn đặc biệt với phụ nữ vùng Kinh Bắc và đồng bằng Bắc Bộ. Nón từng xuất hiện trong đời sống và các sinh hoạt văn hóa dân gian, đặc biệt thường được nhắc đến cùng hình ảnh quan họ Bắc Ninh - Bắc Giang.",
    characteristics: "Nón có dạng rộng và tương đối phẳng, vành lớn, thường được làm từ vật liệu nhẹ như lá hoặc nan. Điểm đặc trưng là hệ thống quai dài, thường có tua hoặc dây trang trí, tạo vẻ mềm mại khi người đội di chuyển.",
    usage_context: "Hội làng, lễ hội dân gian Bắc Bộ, sinh hoạt văn hóa quan họ, biểu diễn nghệ thuật và các hoạt động phục dựng văn hóa truyền thống. Đặc biệt phù hợp với hình ảnh liền chị quan họ.",
    colors: ["Nâu vàng", "Vàng nhạt", "Đen", "Đỏ", "Tím", "Màu tự nhiên của lá và vật liệu đan"],
    accessories: ["Áo tứ thân", "Áo yếm", "Áo dài truyền thống", "Khăn vấn", "Thắt lưng màu", "Trang sức đơn giản"],
    significance: "Là một biểu tượng thị giác quan trọng của văn hóa Kinh Bắc và nghệ thuật dân gian Bắc Bộ. Hình ảnh nón quai thao thường gắn với vẻ đẹp duyên dáng, nền nã của phụ nữ trong không gian quan họ.",
    notes: "Không nên xem nón quai thao là biến thể của nón lá. Đây là hai loại nón có hình dáng, lịch sử và bối cảnh sử dụng khác nhau. Trong hệ thống nên gắn nón quai thao với bối cảnh Bắc Bộ/Kinh Bắc và ưu tiên outfit liên quan đến áo tứ thân, quan họ hoặc văn hóa dân gian Bắc Bộ.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Tư liệu về văn hóa Quan họ Bắc Ninh", "Tư liệu về trang phục và văn hóa dân gian Kinh Bắc", "UNESCO – Dân ca Quan họ Bắc Ninh"],
    type: "headwear",
    category: "headwear",
    gender: "female",
    formality: "Formal",
    image_url: "assets/headwear/h03.png"
  },
  {
    id: "h04_1",
    name: "Mấn",
    origin: "Mấn là loại khăn đội đầu có dạng vành tròn hoặc khối tròn, được tạo bằng cách cuộn và cố định vải thành nhiều lớp. Mấn xuất hiện trong nhiều hình thức trang phục truyền thống và đặc biệt phổ biến trong trang phục cưới hỏi, áo dài và một số hình thức lễ phục của người Việt.",
    characteristics: "Mấn có dạng vòng tròn hoặc vành tròn ôm quanh đầu, thường được tạo từ vải cuộn nhiều lớp. Có loại mấn đơn giản sử dụng vải trơn, cũng có loại được phủ hoặc trang trí bằng hoa văn, thêu, ren, kim tuyến hoặc các vật liệu trang trí khác.",
    usage_context: "Áo dài cưới hỏi, lễ cưới, lễ hội, biểu diễn nghệ thuật, sự kiện văn hóa và các hoạt động tái hiện trang phục truyền thống. Mấn có thể được sử dụng trong các concept trang phục trang trọng.",
    colors: ["Đỏ", "Vàng", "Xanh", "Tím", "Hồng", "Trắng", "Đen", "Màu tương đồng với trang phục"],
    accessories: ["Áo dài", "Áo dài cưới", "Trâm cài tóc", "Hoa cài tóc", "Hoa tai", "Vòng cổ", "Kiềng"],
    significance: "Mấn giúp hoàn thiện kiểu tóc và tạo sự trang trọng cho tổng thể trang phục. Trong trang phục cưới, mấn góp phần thể hiện không khí lễ nghi và nét đẹp truyền thống.",
    notes: "Không nên mặc định mấn là khăn vấn. Khăn vấn thường là dải vải được quấn trực tiếp quanh tóc, trong khi mấn thường có cấu trúc vành hoặc khối được tạo sẵn hoặc cuộn thành vòng. Khi phối với cổ phục cần chọn kiểu mấn phù hợp với thời kỳ, vùng miền và loại trang phục.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Ngàn năm áo mũ – Trần Quang Đức", "Tư liệu về áo dài và trang phục cưới truyền thống Việt Nam"],
    type: "headwear",
    category: "headwear",
    gender: "male",
    formality: "Formal",
    image_url: "assets/headwear/h04_1.png"
  },
  {
    id: "h04_2",
    name: "Mấn",
    origin: "Mấn là loại khăn đội đầu có dạng vành tròn hoặc khối tròn, được tạo bằng cách cuộn và cố định vải thành nhiều lớp. Mấn xuất hiện trong nhiều hình thức trang phục truyền thống và đặc biệt phổ biến trong trang phục cưới hỏi, áo dài và một số hình thức lễ phục của người Việt.",
    characteristics: "Mấn có dạng vòng tròn hoặc vành tròn ôm quanh đầu, thường được tạo từ vải cuộn nhiều lớp. Có loại mấn đơn giản sử dụng vải trơn, cũng có loại được phủ hoặc trang trí bằng hoa văn, thêu, ren, kim tuyến hoặc các vật liệu trang trí khác.",
    usage_context: "Áo dài cưới hỏi, lễ cưới, lễ hội, biểu diễn nghệ thuật, sự kiện văn hóa và các hoạt động tái hiện trang phục truyền thống. Mấn đặc biệt phổ biến khi phối với áo dài trong các dịp cưới hỏi và lễ nghi.",
    colors: ["Đỏ", "Vàng", "Xanh", "Tím", "Hồng", "Trắng", "Đen", "Màu tương đồng với áo dài"],
    accessories: ["Áo dài", "Áo dài cưới", "Trâm cài tóc", "Hoa cài tóc", "Hoa tai", "Vòng cổ", "Kiềng"],
    significance: "Mấn giúp hoàn thiện kiểu tóc và tạo sự trang trọng cho tổng thể trang phục. Trong trang phục cưới, mấn thường góp phần thể hiện không khí lễ nghi, sự trang trọng và nét đẹp truyền thống.",
    notes: "Không nên mặc định mấn là khăn vấn. Khăn vấn thường là dải vải được quấn trực tiếp quanh tóc, trong khi mấn thường có cấu trúc vành hoặc khối được tạo sẵn hoặc cuộn thành vòng. Mấn cưới hiện đại không nên dùng để phục dựng chính xác các kiểu trang phục lịch sử nếu không có căn cứ.",
    references: ["Trang phục Việt Nam – Đoàn Thị Tình", "Ngàn năm áo mũ – Trần Quang Đức", "Tư liệu về áo dài và trang phục cưới truyền thống Việt Nam"],
    type: "headwear",
    category: "headwear",
    gender: "female",
    formality: "Formal",
    image_url: "assets/headwear/h04_2.png"
  }
];